export const reducerConstants = {
    USER_DETAILS: 'USER_DETAILS',

    ADD_EXPERIENCE: 'ADD_EXPERIENCE',
    UPDATE_EXPERIENCE: 'UPDATE_EXPERIENCE',
    DELETE_EXPERIENCE: 'DELETE_EXPERIENCE',

    ADD_EDUCATION: 'ADD_EDUCATION',
    UPDATE_EDUCATION: 'UPDATE_EDUCATION',
    DELETE_EDUCATION: 'DELETE_EDUCATION',

    ADD_COURSE: 'ADD_COURSE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',

    ADD_SOCIAL: 'ADD_SOCIAL',
    UPDATE_SOCIAL: 'UPDATE_SOCIAL',
    DELETE_SOCIAL: 'DELETE_SOCIAL',

    ADD_SKILL: 'ADD_SKILL',
    UPDATE_SKILL: 'UPDATE_SKILL',
    DELETE_SKILL: 'DELETE_SKILL',
   
    ADD_LANGUAGE: 'ADD_LANGUAGE',
    UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
    DELETE_LANGUAGE: 'DELETE_LANGUAGE',
   
    ADD_ACTIVITY: 'ADD_ACTIVITY',
    UPDATE_ACTIVITY: 'UPDATE_ACTIVITY',
    DELETE_ACTIVITY: 'DELETE_ACTIVITY',

    ADD_REFERENCE: 'ADD_REFERENCE',
    UPDATE_REFERENCE: 'UPDATE_REFERENCE',
    DELETE_REFERENCE: 'DELETE_REFERENCE',

    ADD_INTERNSHIP: 'ADD_INTERNSHIP',
    UPDATE_INTERNSHIP: 'UPDATE_INTERNSHIP',
    DELETE_INTERNSHIP: 'DELETE_INTERNSHIP',

    ADD_HOBBY: 'ADD_HOBBY',
   
}
