export const style = {
    mainContainer: `w-full h-screen md:grid md:grid-rows-1 md:grid-cols-2`,
    main: `w-full h-full md:row-span-1 md:col-span-1 bg-white overflow-scroll`,
    displayContainer: `hidden md:block row-span-1 col-span-1 bg-gray-300 bg-gray-300 md:flex items-center justify-center`,
    display: `w-2/3 h-[90vh] grid grid-rows-1 grid-cols-5 rounded-xl`,
    container : `w-full mt-5 p-5`,
    heading: `text-xl font-sans font-semibold mb-3`,
    link: `mt-2 cursor-pointer text-green-700`,
    left: `row-span-1 col-start-1 col-end-3 bg-teal-800 rounded-l-xl flex items-center justify-center `,
    right: `row-span-1 col-start-3 col-end-6 rounded-r-xl bg-white flex items-center justify-center`,
    showContainer: `w-full p-5 border border-gray-200 rounded-lg relative mt-2`,
    wrapper: `w-full flex-row justify-between`,
    inputWrapper: `w-1/2 font-sans text-lg mb-2`,
    dateWrapper: `w-1/2 flex font-sans text-lg mb-2 gap-1`,
    label: `mb-1 block`,
    input: `w-5/6 p-3 bg-gray-100 focus:outline-none`,
    dateContainer: `w-1/3`,
    dateInput: `w-full focus:outline-none bg-gray-100 p-3`,
    icon: `w-8 h-8 absolute right-8 top-4 z-10 cursor-pointer text-green-700`, 
    deleteIcon: `absolute right-0 top-4 z-10 p-2 cursor-pointer text-green-700`,
    plusIcon: `inline text-green-700`,
    bioContainer: `w-full h-[30vh] p-5`, 
    bioWrapper: `w-full text-base font-sans`,
    bioText: `border w-full p-6 focus:outline-none bg-gray-100`,
    textWrapper: 'w-full font-sans text-xs mb-2'
}
  